// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QMSApplication.Models;

#nullable disable

namespace QMSApplication.Migrations
{
    [DbContext(typeof(QMSPortalDbContext))]
    [Migration("20261001044532_UpdateMDDateFields")]
    partial class UpdateMDDateFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("QMSApplication.Models.MDEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssignedTo")
                        .HasColumnType("longtext");

                    b.Property<string>("DeliverableActivity")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("DeliverableActualCompletedDate")
                        .HasColumnType("date");

                    b.Property<string>("DeliverableActualCompletedDateSource")
                        .HasColumnType("longtext");

                    b.Property<string>("DeliverableName")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("DeliverableTargetDate")
                        .HasColumnType("date");

                    b.Property<string>("DeliverableTargetDateSource")
                        .HasColumnType("longtext");

                    b.Property<string>("DeliverableType")
                        .HasColumnType("longtext");

                    b.Property<string>("DeviationReason")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("MilestoneAchievedDate")
                        .HasColumnType("date");

                    b.Property<string>("MilestoneAchievedDateSource")
                        .HasColumnType("longtext");

                    b.Property<string>("MilestoneName")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("MilestoneTargetDate")
                        .HasColumnType("date");

                    b.Property<string>("MilestoneTargetDateSource")
                        .HasColumnType("longtext");

                    b.Property<string>("RecordID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<string>("SNo")
                        .HasColumnType("longtext");

                    b.Property<string>("ScheduleDeviation")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UGs")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MDRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
