// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QMSApplication.Models;

#nullable disable

namespace QMSApplication.Migrations
{
    [DbContext(typeof(QMSPortalDbContext))]
    [Migration("20261001043220_AddMDRecords")]
    partial class AddMDRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("QMSApplication.Models.MDEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssignedTo")
                        .HasColumnType("longtext");

                    b.Property<string>("DeliverableActivity")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeliverableActualCompletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeliverableName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeliverableTargetDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeliverableType")
                        .HasColumnType("longtext");

                    b.Property<string>("DeviationReason")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("MilestoneAchievedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MilestoneName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("MilestoneTargetDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RecordID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<string>("SNo")
                        .HasColumnType("longtext");

                    b.Property<string>("ScheduleDeviation")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UGs")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MDRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
